name: Generate Snake Collaboration Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Schedule to run daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Graph
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}  # Use the repository owner as the GitHub username
          output: dist/snake.svg

      - name: Commit and push Snake Graph
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m "Update Snake Graph"
          git push

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist

      - name: Clean up
        run: rm -rf dist/snake.svg
